const itemsStr =
 `[{"id":1,"FoodName":"Biryani","Cruisine":"Indian","type":"Non-veg","price":699,"description":"felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices"},
{"id":2,"FoodName":"Butter chicken","Cruisine":"Indian","type":"Non-veg","price":689,"description":"pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut"},
{"id":3,"FoodName":"Mutton Curry","Cruisine":"Indian","type":"Non-veg","price":593,"description":"curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam"},
{"id":4,"FoodName":"Rock","Cruisine":"Chinese","type":"Non-veg","price":470,"description":"praesent lectus vestibulum quam sapien varius ut blandit non interdum in"},
{"id":5,"FoodName":"Celie","Cruisine":"Chinese","type":"Veg","price":338,"description":"fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui"},
{"id":6,"FoodName":"Rosalind","Cruisine":"Chinese","type":"Veg","price":541,"description":"eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in"},
{"id":7,"FoodName":"Cold Cocoa Milkshake","Cruisine":"Drinks","type":"Veg","price":375,"description":"enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus"},
{"id":8,"FoodName":"Berke","Cruisine":"Chinese","type":"Non-veg","price":622,"description":"sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia"},
{"id":9,"FoodName":"Mutter Paneer","Cruisine":"Indian","type":"Veg","price":521,"description":"sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue"},
{"id":10,"FoodName":"Chole batora","Cruisine":"Indian","type":"Veg","price":170,"description":"nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus"},
{"id":11,"FoodName":"Kat kat Milkshake with ice cream","Cruisine":"Drinks","type":"Veg","price":332,"description":"hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius"},
{"id":12,"FoodName":"Chocolate milkshake","Cruisine":"Drinks","type":"Veg","price":275,"description":"tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis"},
{"id":13,"FoodName":"Tyne","Cruisine":"Chinese","type":"Veg","price":490,"description":"nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem"},
{"id":14,"FoodName":"Waylon","Cruisine":"Chinese","type":"Non-veg","price":690,"description":"viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere"},
{"id":15,"FoodName":"Rumali Roti","Cruisine":"Breads","type":"veg","price":218,"description":"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien"},
{"id":16,"FoodName":"Terry","Cruisine":"Chinese","type":"Non-veg","price":681,"description":"penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis"},
{"id":17,"FoodName":"Bartolemo","Cruisine":"Chinese","type":"Non-veg","price":165,"description":"sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc"},
{"id":18,"FoodName":"Trey","Cruisine":"Chinese","type":"Non-veg","price":232,"description":"ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse"},
{"id":19,"FoodName":"Alexis","Cruisine":"Drinks","type":"Veg","price":388,"description":"id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu"},
{"id":20,"FoodName":"Tandoori Chicken ","Cruisine":"Indian","type":"Non-veg","price":427,"description":"pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at"},
{"id":21,"FoodName":"Phyllida","Cruisine":"Drinks","type":"Veg","price":630,"description":"nisi eu orci mauris lacinia sapien quis libero nullam sit amet"},
{"id":22,"FoodName":"Chana masala","Cruisine":"Indian","type":"Veg","price":507,"description":"platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at"},
{"id":23,"FoodName":"Chicken Tikka masala","Cruisine":"Indian","type":"Non-veg","price":441,"description":"sit amet nulla quisque arcu libero rutrum ac lobortis vel"},
{"id":24,"FoodName":"Kadai paneer","Cruisine":"Indian","type":"Veg","price":590,"description":"vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum"},
{"id":25,"FoodName":"Oreo milkshake","Cruisine":"Drinks","type":"veg","price":670,"description":"imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet"},
{"id":26,"FoodName":"Ellie","Cruisine":"Chinese","type":"Veg","price":215,"description":"eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci"},
{"id":27,"FoodName":"Mango Milkshake","Cruisine":"Drinks","type":"Veg","price":507,"description":"vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede"},
{"id":28,"FoodName":"Paratha","Cruisine":"Breads","type":"veg","price":660,"description":"bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce"},
{"id":29,"FoodName":"Vanilla milkshake","Cruisine":"Drinks","type":"Veg","price":314,"description":"volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie"},
{"id":30,"FoodName":"Harman","Cruisine":"Chinese","type":"Non-veg","price":355,"description":"sem duis aliquam convallis nunc proin at turpis a pede"},
{"id":31,"FoodName":"Kadai-chicken","Cruisine":"Indian","type":"Non-veg","price":413,"description":"rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin"},
{"id":32,"FoodName":"Melba","Cruisine":"Chinese","type":"Non-veg","price":441,"description":"in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non"},
{"id":33,"FoodName":"Palak Paneer","Cruisine":"Indian","type":"veg","price":203,"description":"risus semper porta volutpat quam pede lobortis ligula sit amet"},
{"id":34,"FoodName":"Scarface","Cruisine":"Chinese","type":"Veg","price":413,"description":"feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna"},
{"id":35,"FoodName":"Boiled Rice","Cruisine":"Indian","type":"veg","price":186,"description":"aliquam non mauris morbi non lectus aliquam sit amet diam"},
{"id":36,"FoodName":"Lyndy","Cruisine":"Chinese","type":"Veg","price":216,"description":"pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti"},
{"id":37,"FoodName":"Dal makhani","Cruisine":"Indian","type":"Veg","price":540,"description":"eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis"},
{"id":38,"FoodName":"Paneer Kulcha","Cruisine":"Breads","type":"veg","price":217,"description":"neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus"},
{"id":39,"FoodName":"Mutton Biryani","Cruisine":"Indian","type":"Non-veg","price":541,"description":"eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus"},
{"id":40,"FoodName":"Naan","Cruisine":"Breads","type":"Veg","price":428,"description":"molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur"}
]`

export default itemsStr;